sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
before_install:
  - nvm install-latest-npm
before_script:
  - 'if [ -n "${ESLINT-}" ]; then npm install --no-save "eslint@${ESLINT}"; fi'
  - 'if [ -n "${AJV-}" ]; then npm install --no-save "ajv@${AJV}"; fi'
  - npm prune > /dev/null && npm ls > /dev/null
script:
  - 'if [ -n "${LINTONLY-}" ]; then npm run lint; else npm run cover && npm run check-coverage; fi'
after_success:
  - npm run travis-after-all
env:
  matrix:
    - ESLINT=6
    - ESLINT=5 AJV=6
matrix:
  include:
    - node_js: "node"
      env: LINTONLY=true
